### ISSUE TITLE
Todos

### ISSUE THREAD

**Issue by sami-29** [sami-29/portfolio#1]
# Main issues
- [x] #2
- [ ] #3
- [ ] #4

## Smaller issues
- [x] text overflows off the carousel.
- [x] carousel doesn't have fixed height and width so it resizes depending on the image.
- [ ] nav-bar open on reload.

### Todos
---
- [x] cursor disappears when outside of window.
- [x] refactoring JavaScript and breaking it down into several files as needed.
- [ ] refactoring SCSS and adding variables.
- [ ] adding responsiveness.
- [ ] adding links to GitHub and LinkedIn and email on the contact "page".
- [x] contact me form working.
- [ ] Making the website more aesthetic.
